name: Docker Build

on:

  workflow_run:
    workflows: ["Backend CI"]
    types:
      - completed

jobs:

  docker:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase owner
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Build Auth Service
        run: |
          docker build \
          -f services/auth-service/Dockerfile \
          -t ghcr.io/$OWNER_LC/auth-service:${{ github.sha }} .

      - name: Push Auth Service
        run: |
          docker push \
          ghcr.io/$OWNER_LC/auth-service:${{ github.sha }}
