apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret
  namespace: backend-platform

type: Opaque

stringData:
  POSTGRES_DB: backend_platform
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
