-- Seed 100 dummy pet products for testing

-- Dogs category products
INSERT INTO products (name, description, sku, price, stock_quantity, category_id) VALUES
('Golden Retriever Bed - Deluxe', 'Premium orthopedic dog bed with memory foam', 'DOG-BED-001', 79.99, 50, (SELECT id FROM categories WHERE name = 'Dogs')),
('Adjustable Dog Collar - Nylon', 'Durable nylon collar with reflective strip', 'DOG-COL-001', 14.99, 100, (SELECT id FROM categories WHERE name = 'Dogs')),
('Dog Training Treats - Chicken', 'High-protein chicken flavored training treats', 'DOG-TRT-001', 12.99, 80, (SELECT id FROM categories WHERE name = 'Dogs')),
('Dog Toy Ball Set - 3 Pack', 'Squeaky balls for interactive play', 'DOG-TOY-001', 9.99, 120, (SELECT id FROM categories WHERE name = 'Dogs')),
('Dog Leash - Heavy Duty', 'Strong 6ft leash with handle grip', 'DOG-LESH-001', 24.99, 60, (SELECT id FROM categories WHERE name = 'Dogs')),
('Dog House - Wooden', 'Weatherproof wooden dog house with roof', 'DOG-HSE-001', 149.99, 25, (SELECT id FROM categories WHERE name = 'Dogs')),
('Dog Shampoo - Organic', 'Natural dog shampoo with tea tree oil', 'DOG-SHP-001', 18.99, 70, (SELECT id FROM categories WHERE name = 'Dogs')),
('Dog Brush - Slicker', 'Professional grooming brush for all coat types', 'DOG-BRS-001', 22.99, 45, (SELECT id FROM categories WHERE name = 'Dogs')),
('Dog Food Bowl Set', 'Stainless steel dual bowl feeder', 'DOG-BOWL-001', 29.99, 90, (SELECT id FROM categories WHERE name = 'Dogs')),
('Dog ID Tag - Metal', 'Personalized metal dog ID tag', 'DOG-TAG-001', 8.99, 150, (SELECT id FROM categories WHERE name = 'Dogs')),
('Dog Crate - Medium', 'Portable collapsible dog crate', 'DOG-CRT-001', 89.99, 35, (SELECT id FROM categories WHERE name = 'Dogs')),
('Dog Jacket - Waterproof', 'Waterproof winter jacket for dogs', 'DOG-JKT-001', 44.99, 55, (SELECT id FROM categories WHERE name = 'Dogs')),
('Dog Dental Chew Toys', 'Teeth cleaning chew toys pack', 'DOG-DCH-001', 16.99, 85, (SELECT id FROM categories WHERE name = 'Dogs')),
('Dog Harness - No-Pull', 'Comfortable no-pull harness', 'DOG-HRN-001', 34.99, 75, (SELECT id FROM categories WHERE name = 'Dogs')),
('Dog Bed - Memory Foam', 'Cooling memory foam dog bed', 'DOG-BED-002', 59.99, 40, (SELECT id FROM categories WHERE name = 'Dogs')),
('Dog Treat Dispenser Toy', 'Interactive treat dispensing toy', 'DOG-TDT-001', 19.99, 65, (SELECT id FROM categories WHERE name = 'Dogs')),
('Dog Paw Cleaner', 'Portable paw cleaning cup', 'DOG-PAW-001', 13.99, 110, (SELECT id FROM categories WHERE name = 'Dogs')),
('Dog Tick Removal Tool', 'Safe tick removal device', 'DOG-TIK-001', 11.99, 95, (SELECT id FROM categories WHERE name = 'Dogs')),
('Dog Training Clicker', 'Clicker for dog behavior training', 'DOG-CLK-001', 6.99, 200, (SELECT id FROM categories WHERE name = 'Dogs')),
('Dog Coat - Fleece', 'Soft fleece winter coat', 'DOG-COT-001', 39.99, 50, (SELECT id FROM categories WHERE name = 'Dogs')),

-- Cats category products
('Cat Litter Box - Hooded', 'Large hooded litter box with filter', 'CAT-LTR-001', 34.99, 60, (SELECT id FROM categories WHERE name = 'Cats')),
('Cat Food - Salmon', 'Premium salmon flavored cat food', 'CAT-FD-001', 22.99, 100, (SELECT id FROM categories WHERE name = 'Cats')),
('Cat Toy Mouse - Plush', 'Soft plush mouse toy with catnip', 'CAT-TOY-001', 7.99, 150, (SELECT id FROM categories WHERE name = 'Cats')),
('Cat Scratch Post - Tall', 'Tall scratching post with sisal rope', 'CAT-SCP-001', 49.99, 40, (SELECT id FROM categories WHERE name = 'Cats')),
('Cat Bed - Donut', 'Cozy donut-shaped cat bed', 'CAT-BED-001', 28.99, 75, (SELECT id FROM categories WHERE name = 'Cats')),
('Cat Collar - Bell', 'Adjustable collar with safety bell', 'CAT-COL-001', 9.99, 120, (SELECT id FROM categories WHERE name = 'Cats')),
('Cat Water Fountain', 'Electric ceramic water fountain', 'CAT-WTR-001', 54.99, 50, (SELECT id FROM categories WHERE name = 'Cats')),
('Cat Grooming Brush', 'Gentle slicker brush for cats', 'CAT-BRS-001', 16.99, 80, (SELECT id FROM categories WHERE name = 'Cats')),
('Cat Feather Toy', 'Interactive feather wand toy', 'CAT-FTR-001', 11.99, 90, (SELECT id FROM categories WHERE name = 'Cats')),
('Cat Nail Clipper', 'Professional cat nail clipper', 'CAT-NCL-001', 14.99, 70, (SELECT id FROM categories WHERE name = 'Cats')),
('Cat Hammock - Window', 'Sunny window mount cat hammock', 'CAT-HMK-001', 24.99, 55, (SELECT id FROM categories WHERE name = 'Cats')),
('Cat Litter Scoop', 'Ergonomic litter scoop', 'CAT-SCP-001', 8.99, 110, (SELECT id FROM categories WHERE name = 'Cats')),
('Cat Toy Ball - Jingle', 'Jingle bell balls for cats', 'CAT-JBL-001', 6.99, 140, (SELECT id FROM categories WHERE name = 'Cats')),
('Cat Tree - 3 Level', '3-level cat tree with hideaway', 'CAT-TRE-001', 79.99, 35, (SELECT id FROM categories WHERE name = 'Cats')),
('Cat Treats - Tuna', 'Crunchy tuna flavored treats', 'CAT-TRT-001', 9.99, 100, (SELECT id FROM categories WHERE name = 'Cats')),
('Cat Carrier - Soft', 'Soft-sided travel carrier', 'CAT-CAR-001', 39.99, 45, (SELECT id FROM categories WHERE name = 'Cats')),
('Cat Eye Cleaner', 'Gentle eye cleaning solution', 'CAT-EYE-001', 12.99, 85, (SELECT id FROM categories WHERE name = 'Cats')),
('Cat ID Tag - Engraved', 'Personalized engraved cat tag', 'CAT-TAG-001', 10.99, 130, (SELECT id FROM categories WHERE name = 'Cats')),
('Cat Teaser Toy - String', 'String teaser toy for cats', 'CAT-TSR-001', 8.99, 95, (SELECT id FROM categories WHERE name = 'Cats')),
('Cat Bed - Cave', 'Cozy cave-style cat bed', 'CAT-BED-002', 33.99, 60, (SELECT id FROM categories WHERE name = 'Cats')),

-- Birds category products
('Bird Cage - Large', 'Spacious bird cage with perches', 'BRD-CAG-001', 129.99, 20, (SELECT id FROM categories WHERE name = 'Birds')),
('Bird Food - Premium Mix', 'Premium bird seed mix', 'BRD-FD-001', 18.99, 80, (SELECT id FROM categories WHERE name = 'Birds')),
('Bird Perch - Natural Wood', 'Natural wood bird perch', 'BRD-PRC-001', 14.99, 60, (SELECT id FROM categories WHERE name = 'Birds')),
('Bird Toy - Bell', 'Hanging bell toy for birds', 'BRD-TOY-001', 9.99, 100, (SELECT id FROM categories WHERE name = 'Birds')),
('Bird Water Dish', 'Stainless steel water dish', 'BRD-WTR-001', 7.99, 120, (SELECT id FROM categories WHERE name = 'Birds')),
('Bird Food Dish', 'Easy-fill food dish for birds', 'BRD-FDH-001', 8.99, 110, (SELECT id FROM categories WHERE name = 'Birds')),
('Bird Swing - Rope', 'Rope swing for bird cages', 'BRD-SWG-001', 11.99, 75, (SELECT id FROM categories WHERE name = 'Birds')),
('Bird Mirror Toy', 'Reflective mirror toy for birds', 'BRD-MIR-001', 10.99, 90, (SELECT id FROM categories WHERE name = 'Birds')),
('Bird Nesting Box', 'Wooden nesting box for small birds', 'BRD-NST-001', 24.99, 40, (SELECT id FROM categories WHERE name = 'Birds')),
('Bird Ladder - Wood', 'Wooden climbing ladder', 'BRD-LAD-001', 13.99, 65, (SELECT id FROM categories WHERE name = 'Birds')),
('Bird Treat - Millet', 'Spray millet bird treats', 'BRD-TRT-001', 6.99, 130, (SELECT id FROM categories WHERE name = 'Birds')),
('Bird Cage Liner', 'Disposable cage liners pack', 'BRD-LNR-001', 12.99, 85, (SELECT id FROM categories WHERE name = 'Birds')),
('Bird Cuttlebone', 'Calcium-rich cuttlebone', 'BRD-CUT-001', 5.99, 150, (SELECT id FROM categories WHERE name = 'Birds')),
('Bird Toy - Chew Blocks', 'Wooden chew blocks for birds', 'BRD-CHW-001', 8.99, 100, (SELECT id FROM categories WHERE name = 'Birds')),
('Bird Vitamin Supplement', 'Multi-vitamin powder for birds', 'BRD-VIT-001', 16.99, 55, (SELECT id FROM categories WHERE name = 'Birds')),

-- Fish category products
('Aquarium - 20 Gallon', '20 gallon glass aquarium kit', 'FIS-AQU-001', 89.99, 30, (SELECT id FROM categories WHERE name = 'Fish')),
('Aquarium Filter - Canister', 'Powerful canister filter', 'FIS-FLT-001', 79.99, 25, (SELECT id FROM categories WHERE name = 'Fish')),
('Aquarium Heater - 100W', '100-watt aquarium heater', 'FIS-HT-001', 34.99, 50, (SELECT id FROM categories WHERE name = 'Fish')),
('Aquarium Air Pump', 'Air pump for aeration', 'FIS-AIR-001', 29.99, 45, (SELECT id FROM categories WHERE name = 'Fish')),
('Aquarium Gravel - Black', 'Black decorative aquarium gravel', 'FIS-GRV-001', 16.99, 70, (SELECT id FROM categories WHERE name = 'Fish')),
('Aquarium Plant - Anubias', 'Live anubias aquarium plant', 'FIS-PLT-001', 12.99, 80, (SELECT id FROM categories WHERE name = 'Fish')),
('Aquarium Decoration - Cave', 'Resin cave decoration', 'FIS-DEC-001', 22.99, 60, (SELECT id FROM categories WHERE name = 'Fish')),
('Aquarium Light - LED', 'LED aquarium light strip', 'FIS-LT-001', 44.99, 40, (SELECT id FROM categories WHERE name = 'Fish')),
('Fish Food - Flakes', 'General purpose fish food flakes', 'FIS-FD-001', 8.99, 110, (SELECT id FROM categories WHERE name = 'Fish')),
('Aquarium Thermometer', 'Adhesive thermometer for tank', 'FIS-THM-001', 6.99, 120, (SELECT id FROM categories WHERE name = 'Fish')),
('Aquarium Net - Fine Mesh', 'Fine mesh fish net', 'FIS-NET-001', 7.99, 100, (SELECT id FROM categories WHERE name = 'Fish')),
('Aquarium Bucket - 5L', 'Dedicated aquarium water bucket', 'FIS-BCK-001', 14.99, 75, (SELECT id FROM categories WHERE name = 'Fish')),
('Aquarium Water Conditioner', 'Dechlorinator water conditioner', 'FIS-CND-001', 11.99, 90, (SELECT id FROM categories WHERE name = 'Fish')),
('Aquarium Test Kit - pH', 'pH level testing kit', 'FIS-TST-001', 18.99, 55, (SELECT id FROM categories WHERE name = 'Fish')),
('Aquarium Siphon - Python', 'Python aquarium siphon', 'FIS-SPH-001', 39.99, 35, (SELECT id FROM categories WHERE name = 'Fish')),
('Aquarium Stand - Black', 'Black aquarium stand', 'FIS-STD-001', 99.99, 20, (SELECT id FROM categories WHERE name = 'Fish')),
('Fish Food - Pellets', 'Sinking pellet fish food', 'FIS-PLS-001', 9.99, 95, (SELECT id FROM categories WHERE name = 'Fish')),
('Aquarium Plant - Java Fern', 'Live java fern plant', 'FIS-JFN-001', 10.99, 85, (SELECT id FROM categories WHERE name = 'Fish')),

-- Pet Food category products
('Premium Dog Food - Grain Free', 'High-protein grain-free dog food 30lb', 'PF-DG-001', 64.99, 30, (SELECT id FROM categories WHERE name = 'Pet Food')),
('Cat Food - Indoor Formula', 'Indoor cat formula 15lb bag', 'PF-CT-001', 45.99, 40, (SELECT id FROM categories WHERE name = 'Pet Food')),
('Bird Seed - Premium Mix', 'Premium wild bird seed mix 20lb', 'PF-BR-001', 34.99, 50, (SELECT id FROM categories WHERE name = 'Pet Food')),
('Rabbit Pellets - Organic', 'Organic rabbit feed 10lb', 'PF-RB-001', 28.99, 35, (SELECT id FROM categories WHERE name = 'Pet Food')),
('Guinea Pig Food Mix', 'Complete guinea pig diet 8lb', 'PF-GP-001', 19.99, 55, (SELECT id FROM categories WHERE name = 'Pet Food')),
('Hamster Mix - Deluxe', 'Deluxe hamster seed mix 5lb', 'PF-HM-001', 14.99, 70, (SELECT id FROM categories WHERE name = 'Pet Food')),
('Dog Wet Food - Chicken', 'Wet dog food 12 cans', 'PF-DG-002', 24.99, 80, (SELECT id FROM categories WHERE name = 'Pet Food')),
('Cat Wet Food - Tuna', 'Wet cat food 12 cans', 'PF-CT-002', 19.99, 90, (SELECT id FROM categories WHERE name = 'Pet Food')),

-- Remaining variety products
('Pet Grooming Kit - Complete', 'Complete grooming kit with 10 tools', 'ACC-GRM-001', 39.99, 45, (SELECT id FROM categories WHERE name = 'Dogs')),
('Pet First Aid Kit', 'Comprehensive pet first aid kit', 'ACC-FAD-001', 29.99, 40, (SELECT id FROM categories WHERE name = 'Cats')),
('Pet Carrier - Backpack', 'Cat/small pet backpack carrier', 'ACC-BKP-001', 44.99, 35, (SELECT id FROM categories WHERE name = 'Cats')),
('Pet Gate - Expandable', 'Expandable safety gate', 'ACC-GTE-001', 49.99, 50, (SELECT id FROM categories WHERE name = 'Dogs')),
('Pet Playpen - Portable', 'Portable pet playpen', 'ACC-PPN-001', 59.99, 30, (SELECT id FROM categories WHERE name = 'Dogs')),
('Pet Blanket - Waterproof', 'Waterproof pet blanket', 'ACC-BLK-001', 34.99, 60, (SELECT id FROM categories WHERE name = 'Dogs')),
('Pet Odor Eliminator', 'Natural pet odor spray', 'ACC-ODE-001', 16.99, 75, (SELECT id FROM categories WHERE name = 'Dogs')),
('Pet Stain Remover', 'Enzymatic stain remover', 'ACC-STN-001', 14.99, 85, (SELECT id FROM categories WHERE name = 'Cats')),
('Pet Toothbrush Set', 'Dual-headed pet toothbrush', 'ACC-TBR-001', 12.99, 100, (SELECT id FROM categories WHERE name = 'Dogs')),
('Pet Waste Bag Dispenser', 'Waste bag dispenser with bags', 'ACC-WST-001', 9.99, 120, (SELECT id FROM categories WHERE name = 'Dogs')),
('Pet Bed Warmer - Electric', 'Electric pet bed warmer', 'ACC-WRM-001', 42.99, 40, (SELECT id FROM categories WHERE name = 'Dogs')),
('Pet Camera - WiFi', 'WiFi pet monitoring camera', 'ACC-CAM-001', 99.99, 25, (SELECT id FROM categories WHERE name = 'Dogs')),
('Pet GPS Tracker', 'GPS tracking collar for pets', 'ACC-GPS-001', 89.99, 30, (SELECT id FROM categories WHERE name = 'Dogs')),
('Pet Microchip Reader', 'Universal microchip scanner', 'ACC-MCP-001', 59.99, 20, (SELECT id FROM categories WHERE name = 'Cats')),
('Pet Nail File - Electric', 'Electric pet nail file', 'ACC-NFE-001', 32.99, 50, (SELECT id FROM categories WHERE name = 'Dogs')),
('Pet Hair Vacuum - Portable', 'Portable handheld pet hair vacuum', 'ACC-VAC-001', 49.99, 35, (SELECT id FROM categories WHERE name = 'Dogs')),
('Pet Mat - Waterproof', 'Large waterproof pet mat', 'ACC-MAT-001', 29.99, 55, (SELECT id FROM categories WHERE name = 'Dogs')),
('Pet Food Storage Container', 'Airtight pet food storage', 'ACC-STG-001', 22.99, 70, (SELECT id FROM categories WHERE name = 'Pet Food')),
('Pet Lunch Box - Portable', 'Portable pet meal box', 'ACC-LBX-001', 18.99, 80, (SELECT id FROM categories WHERE name = 'Pet Food')),
('Pet Calming Spray', 'Natural calming spray for pets', 'ACC-CLM-001', 13.99, 95, (SELECT id FROM categories WHERE name = 'Dogs')),
('Pet Bed - Raised Platform', 'Raised cooling pet bed', 'ACC-RSD-001', 54.99, 40, (SELECT id FROM categories WHERE name = 'Dogs'))
ON CONFLICT (sku) DO NOTHING;
