ALTER TABLE payment_settings
    ADD COLUMN IF NOT EXISTS net_banking_active BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS credit_card_active BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS debit_card_active BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS qr_code_active BOOLEAN NOT NULL DEFAULT TRUE;